<a href="https://colab.research.google.com/github/shrutijadhav25-cell/Data_science_lab_SE_A_69/blob/main/3x3withfunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([
    [1, 2, 3],
    [5, 6, 4],
    [1, 3, 2]
])

print("Original 3x3 Matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")

Original 3x3 Matrix:
[[1 2 3]
 [5 6 4]
 [1 3 2]]

Determinant of the matrix: 14.999999999999993
