<a href="https://colab.research.google.com/github/shrutijadhav25-cell/Data_science_lab_SE_A_69/blob/main/inversewithnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Input 3x3 matrix
A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

det = np.linalg.det(A)

if det == 0:
    print("Matrix is not invertible (determinant is 0).")
else:
    A_inv = np.linalg.inv(A)
    print("Inverse of the matrix:")
    print(A_inv)

Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
